/*
 * Generated by export_generator.dart
 * Do not edit this file manually.
 * To regenerate, run `dart run .\scripts\export_generator.dart`
 */

export 'package:wfmge/src/services/config/preferences.dart';
